### DISCUSSION TITLE
How to put the nightly flags on .cargo/config.toml

### DISCUSSION THREAD

**Discussion by lucascompython** [johnthagen/min-sized-rust#77] [Q&A] [answered]
I'm building a tauri app and on android using the following command: `cargo tauri android build --target aarch64` I can't supply -- -Z flags, I'll get this error: `error: unexpected argument '-Z' found`.  
Maybe there is a way to provide them in the config.toml file?

**Comment by NobodyXu** [comment]
I think the following would work:

```
cargo +nightly tauri android build --target aarch64 -Z...
```

**Comment by lucascompython** [comment, marked as answer]
I've found that if I put this in `cargo.toml`:
```toml
[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size", "panic_immediate_abort"]
trim-paths = true
```
It works.
Thanks!
